sparkmaster:
  image: "farismosman/piospark"
  container_name: piosparkmaster
  net: "pionetwork"
  ports:
    - "8080:8080"
  command: "/start.sh master"

sparkslave:
  image: "farismosman/piospark"
  net: "pionetwork"
  ports:
    - "8081:8081"
    - "4040:4040"
  command: "/start.sh slave"
