config:
  image: "farismosman/config"
  container_name: config
  volumes:
    - /tmp/config:/etc/config

sparkmaster:
  image: "farismosman/spark:1.6.3"
  container_name: sparkmaster
  hostname: sparkmaster
  env_file: .master-env
  net: pionetwork
  volumes:
    - /tmp/config/spark:/etc/config/spark
  ports:
    - "8080:8080"
  command: "/start.sh master"

sparkslave:
  image: "farismosman/spark:1.6.3"
  container_name: sparkslave
  hostname: sparkslave
  env_file: .slave-env
  net: pionetwork
  volumes:
    - /tmp/config/spark:/etc/config/spark
  ports:
    - "8081:8081"
    - "4040:4040"
  command: "/start.sh slave"

sparkcron:
  image: "farismosman/cron"
  container_name: sparkcron
  hostname: sparkcron
  net: pionetwork
  env_file: .cron-env
